version: '3'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    environment:
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=data
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
